services:
  postgres:
    image: postgres:16-alpine
    container_name: sentinela-db
    environment:
      POSTGRES_DB: sentinela
      POSTGRES_USER: sentinela
      POSTGRES_PASSWORD: sentinela123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sentinela -d sentinela"]
      interval: 5s
      timeout: 5s
      retries: 5

  sentinela-soap:
    build: ./sentinela-soap
    container_name: sentinela-soap
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sentinela-db:5432/sentinela
      - SPRING_DATASOURCE_USERNAME=sentinela
      - SPRING_DATASOURCE_PASSWORD=sentinela123
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8081/ws/alerta.wsdl"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  sentinela-orbital:
    build: ./sentinela-orbital
    container_name: sentinela-orbital
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sentinela-db:5432/sentinela
      - SPRING_DATASOURCE_USERNAME=sentinela
      - SPRING_DATASOURCE_PASSWORD=sentinela123
      - SOAP_URL=http://sentinela-soap:8081/ws
    depends_on:
      sentinela-soap:
        condition: service_healthy
      postgres:
        condition: service_healthy

volumes:
  pgdata:
